@startuml
class EZGas{

}
class Developer{
	+ Name
	+ Surname
	+ SSN
	+ Salary
}
class User {
	+ Phone_Id
}
class PersonalAccount {
	+ Id
	+ Name
	+ Surname
	+ SSN
	+ Role
}
class GasStation{
	+ Latitude
	+ Longitude
}
class Gas{
	+ Type
	+ Price
}

note "Role can be Registered User or Gas Station Manager" as N1
PersonalAccount -- N1

User o-- PersonalAccount
GasStation --"*" Gas :"can provide"
EZGas --"*" User
EZGas --"*" GasStation
EZGas --"*" Developer : "working on it"
PersonalAccount --"*" GasStation : "notifies presence of	"
@enduml
