@startuml
left to right direction
actor Gas_Station_Manager as gsm
actor Map_System as ms
actor Driver_registered as drvR
actor Driver_unregistered as drvUR
drvR -- (FR1 Record a new gas station with its relative informations --> User Side)
(FR1 Record a new gas station with its relative informations --> User Side) <|-- (FR9 Update a gas station informations) : <<extends>>
gsm -- (FR2 Record a new gas station with its relative informations --> Gas Station Manager Side)
(FR2 Record a new gas station with its relative informations --> Gas Station Manager Side) <|-- (FR9 Update a gas station informations) : <<extends>>
drvR -- (FR3 Produce a report about correctness of the informations about a gas station)
drvUR -- (FR3 Produce a report about correctness of the informations about a gas station)
drvR -- (FR4 Produce a report about suggestions for the application)
drvUR -- (FR4 Produce a report about suggestions for the application)
gsm -- (FR4 Produce a report about suggestions for the application)
drvR -- (FR5 Manage accounts)
drvUR -- (FR5 Manage accounts)
gsm -- (FR5 Manage accounts)
(FR5 Manage accounts) --> (FR5.1 Create account) :<<include>>
(FR5 Manage accounts) --> (FR5.2 Edit account) :<<include>>
(FR5 Manage accounts) --> (FR5.1 Delete account) :<<include>>
drvR -- (FR6 Manage gas station locations in DB and display them on a map)
drvUR -- (FR6 Manage gas station locations in DB and display them on a map)
(FR6 Manage gas station locations in DB and display them on a map) -- ms
@enduml
